In [42]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [43]:
x_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [44]:
print("Elements of x_train : \n", x_train[:10])
print("\nElements of y_train : \n", y_train[:10])
print ('\nThe shape of x_train is:', x_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(x_train))

Elements of x_train : 
 [[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [0 1 1]
 [0 0 0]
 [1 0 1]
 [0 1 0]
 [1 0 0]]

Elements of y_train : 
 [1 1 0 0 1 0 0 1 1 0]

The shape of x_train is: (10, 3)
The shape of y_train is:  (10,)
Number of training examples (m): 10


In [45]:
def entropy(y):
    p1 = 0
    ent = 0
    if len(y) != 0:
        p1 = len(y[y == 1]) / len(y)
        
    if p1 != 0 and p1 != 1:
        ent = - p1*np.log2(p1) - (1-p1)*np.log2(1-p1)
      
    else:
        ent = 0
        
    return ent  

In [46]:
print("Entropy at root node is : ", entropy(y_train))

Entropy at root node is :  1.0


In [47]:
def split_data(x, node_indices, feature):
    left = []
    right = []
    for i in node_indices:
        if(x[i][feature] == 1):
            left.append(i)
            
        else:
            right.append(i)
            
    return left, right    

In [48]:
root_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
feature = 2
left, right = split_data(x_train, root_indices, feature)
print("CASE 1:")
print("Left indices: ", left)
print("Right indices: ", right)

root_indices_subset = [0, 2, 4, 6, 8]
left, right = split_data(x_train, root_indices_subset, feature)

print("CASE 2:")
print("Left indices: ", left)
print("Right indices: ", right)

CASE 1:
Left indices:  [0, 1, 4, 5, 7]
Right indices:  [2, 3, 6, 8, 9]
CASE 2:
Left indices:  [0, 4]
Right indices:  [2, 6, 8]


In [49]:
def info_gain(x, y, node_indices, feature):
    left, right = split_data(x, node_indices, feature)
    x_node, y_node = x[node_indices], y[node_indices]
    x_left, y_left = x[left], y[left]
    x_right, y_right = x[right], y[right]
    
    info = 0
    
    node_entropy = entropy(y_node)
    left_entropy = entropy(y_left)
    right_entropy = entropy(y_right)
    w_left = len(x_left) / len(x_node)
    w_right = len(x_right) / len(x_node)
    weighted_entropy =  w_left * left_entropy + w_right * right_entropy
    info = node_entropy - weighted_entropy
    
    return info

In [50]:
info_gain0 = info_gain(x_train, y_train, root_indices, feature=0)
print("Information Gain from splitting the root on brown cap: ", info_gain0)

info_gain1 = info_gain(x_train, y_train, root_indices, feature=1)
print("Information Gain from splitting the root on tapering stalk shape: ", info_gain1)

info_gain2 = info_gain(x_train, y_train, root_indices, feature=2)
print("Information Gain from splitting the root on solitary: ", info_gain2)

max_info = max(info_gain0, info_gain1, info_gain2)
print("Maximum info gain is : ", max_info)

Information Gain from splitting the root on brown cap:  0.034851554559677034
Information Gain from splitting the root on tapering stalk shape:  0.12451124978365313
Information Gain from splitting the root on solitary:  0.2780719051126377
Maximum info gain is :  0.2780719051126377


In [51]:
def best_feature(max_info, x, y, node_indices):
    temp = x.shape[1]
    best_feature = -1
    for feature in range(temp):
        info = info_gain(x, y, node_indices, feature)
        if info == max_info:
            best_feature = feature
            
            
    return best_feature

In [52]:
best_feature = best_feature(max_info, x_train, y_train, root_indices)
print("Best feature to split on: %d" % best_feature)

Best feature to split on: 2


In [53]:
tree = []
def build_tree_recursive(x, y, node_indices, branch_name, max_depth, current_depth):
    if current_depth == max_depth:
        formatting = " "*current_depth + "-"*current_depth
        print(formatting, "%s leaf node with indices" % branch_name, node_indices)
        return
     
    best_feature = 2
    
    formatting = "-"*current_depth
    print("%s Depth %d, %s: Split on feature: %d" % (formatting, current_depth, branch_name, best_feature))
    
    left, right = split_data(x, node_indices, best_feature)
    tree.append((left, right, best_feature))
    
    build_tree_recursive(x, y, left, "Left", max_depth, current_depth+1)
    build_tree_recursive(x, y, right, "Right", max_depth, current_depth+1)
    

In [54]:

build_tree_recursive(x_train, y_train, root_indices, "Root", max_depth=2, current_depth=0)

 Depth 0, Root: Split on feature: 2
- Depth 1, Left: Split on feature: 2
  -- Left leaf node with indices [0, 1, 4, 5, 7]
  -- Right leaf node with indices []
- Depth 1, Right: Split on feature: 2
  -- Left leaf node with indices []
  -- Right leaf node with indices [2, 3, 6, 8, 9]
